// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmdgogbnptgfwgcdgruh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtZGdvZ2JucHRnZndnY2RncnVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMTUyMDEsImV4cCI6MjA2NDg5MTIwMX0.DtSmnXkyD9m03RLRb6LGhqtmpFTKvh-4qPHLMr6AmGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);